_target_: flava.definitions.FLAVAArguments
training:
  _target_: flava.definitions.TrainingArguments
  lightning:
    max_steps: 450000
    gpus: [6]
    progress_bar_refresh_rate: 1
    val_check_interval: 450000
    num_sanity_val_steps: 0
    #strategy: ddp
  lightning_checkpoint: 
    dirpath: "./checkpoint/all_transfer_market"
    filename: flava-{epoch:02d}-{step}
    save_last: true
    every_n_train_steps: 1000
    save_on_train_epoch_end: true
    verbose: true
  lightning_load_from_checkpoint: null
  seed: -1
  batch_size: 16
  num_workers: 4
  learning_rate: 2e-4
  adam_eps: 1e-8
  adam_weight_decay: 1e-2
  warmup_steps: 2000

datasets:
  _target_: flava.definitions.TrainingDatasetsInfo
  selected:  
  - image
  - text
  - myvl
  image:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.HFDatasetInfo
        key: transfer_market_image
        subset: default
        rename_columns:
          - ["image_id", "label"]
    val:
      - _target_: flava.definitions.HFDatasetInfo
        key: transfer_market_image
        subset: default
        rename_columns:
          - ["image_id", "label"]
        split_key_mapping:
          validation: train
  text:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.HFDatasetInfo
        key: transfer_market_text
        subset: default
    val:
      - _target_: flava.definitions.HFDatasetInfo
        key: transfer_market_text
        subset: default
        split_key_mapping:
          validation: train
    datamodule_extra_kwargs:
      text_columns: ["text"]
  myvl:
    _target_: flava.definitions.TrainingSingleDatasetInfo
    train:
      - _target_: flava.definitions.HFDatasetInfo
        key: transfer_market
        subset: default
    val:
      - _target_: flava.definitions.HFDatasetInfo
        key: transfer_market
        subset: default
        split_key_mapping:
          validation: train
